CREATE SCHEMA dev;  
GO  
CREATE SEQUENCE dev.AutoNum
    AS int  
    START WITH 1  
    INCREMENT BY 1 ;  
GO 
CREATE TABLE dev.USUARIOS (
	UsuID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	UsuNombre INT NOT NULL DEFAULT (NEXT VALUE FOR dev.AutoNum),
	UsuPass VARCHAR(20) NOT NULL
);
GO
CREATE TABLE dev.PRODUCTO (
	ProID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ProDesc VARCHAR(50) NULL,
	ProValor MONEY NOT NULL
);
GO
CREATE TABLE dev.PEDIDO (
	PedID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PedUsu INT NOT NULL,
	PedProd INT NOT NULL,
	PedVrUnit Money NOT NULL,
	PedCant FLOAT NOT NULL,
	PedSubTot MONEY NOT NULL,
	PedIVA FLOAT NULL,
	PedTotal MONEY NOT NULL,
	FOREIGN KEY (PedUsu) REFERENCES dev.USUARIOS(UsuID),
	FOREIGN KEY (PedProd) REFERENCES dev.PRODUCTO(ProID)
);
GO